spring.application.name=buguinho

spring.config.import=optional:file:./buguinho/src/main/java/io/github/henriques/buguinho/config/application-secrets.properties

spring.data.mongodb.database=buguinho
